spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_app
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=never

jwt.secret=O9hxNvUQ9RTV6c0crg4GRL3YsKlXvzUf8+51INLqjy1BPjibmL21UYoDwZ7EEEnSr3HFumd5yowckDAyYO+ISA==
jwt.expiration-ms=15552000000

admin.default.username=test-admin
admin.default.password=admin