spring.application.name=RestaurantBackend

# Datasource
#spring.datasource.url=jdbc:h2:file:./data/restaurantdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=androidsql

# H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL init
spring.sql.init.mode=never

# JWT
jwt.secret=Wx4oEbr3Y/1WOFKOuPi/CXr2XpLM6gXobs+Tpp0pvL0=
jwt.expiration-ms=15552000000